schedule/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace="shedule")),
    path('admin/', admin.site.urls),
    path('api/', include('tasks.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

tasks/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from tasks import views

app_name = "shedule"

urlpatterns = [
    path('shedule/add', views.shedule_add, name = 'shedule_add'),
    path('user/add', views.user_add, name = 'user_add'),
    path('schedule/', views.ScheduleList.as_view()),
    path('schedule/<int:pk>/', views.ScheduleDetail.as_view()),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile (models.Model):
    KURS_SOURCES = (
        ('python', 'Python'),
        ('c_plus', 'C++'),
        ('php', 'PHP'),
        ('java', 'JAVA'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Препод')
    kurs = models.CharField(max_length=50, verbose_name='Курс', choices=KURS_SOURCES)
    
    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профиль'

    def __str__(self):
        return "%d) %s  %s" % (self.id, self.user, self.kurs)

@receiver(post_save, sender = User)
def creat_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user = instance)

@receiver(post_save, sender = User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()



class Schedule(models.Model):
    data_first = models.DateTimeField()
    data_second = models.DateTimeField()
    event = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '5'),
    )
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)

tasks/forms.py
from django import forms
from .models import *
from django.core.validators import RegexValidator
import re


# class SheduleAdd(forms.ModelForm):
   
#     class Meta:
#         model = ProductModel
#         fields = "__all__"

class UserAdd(forms.ModelForm):
   
    class Meta:
        model = Profile
        fields = "__all__"

tasks/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from .forms import *
from .models import *
# Create your views here.
def user_add(request):
    context = {}    
    
    form = UserAdd(request.POST or None)
    
    if request.method == 'POST' and form.is_valid():
        form1 = form.save()
        context['form'] = form
        context['saved'] = True
        context['resault'] = form1
        context['title'] = 'Добавить Препода'
        return render(request, 'add_shedule.html', context)
        
    if request.method == 'GET':
        context['form'] = form
        context['title'] = 'Добавить Препода'

    return render(request, 'add_shedule.html', context)

def shedule_add(request):
    context = {}    
    context['title'] = 'Добавить Задание'

    return render(request, 'add_shedule.html', context)

from django.shortcuts import render
from rest_framework import generics
from .models import *
from .serializers import ScheduleSerializer
from django.contrib.auth.models import User
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse


class ScheduleList(generics.ListCreateAPIView):
    queryset = Schedule.objects.all()
    serializer_class = ScheduleSerializer

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

class ScheduleDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Schedule.objects.all()
    serializer_class = ScheduleSerializer

@api_view(['GET'])
def api_root(request, format=None):
    return Response({

        'schedule': reverse('schedule-list', request=request, format=format)
    })

tasks/templates/add_shedule.html
{% extends 'base.html' %}

{% block title %} {{title}} {% endblock %}

{% block content %}

{% for v in form.error %}
    {{ v }}
{% endfor %}

{% if saved%}
<p class="bg-danger" style="padding: 10px; border-radius: 5px;">{{resault.name}} - {{resault.intager}} Добавлен</p>
{% endif %}

{% if form %}
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
        
    <button type="submit">ОК</button>
</form>
{% endif %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>sd</title>
</head>
<body>

    <div class="row">
        <div class="col-md-2">
            <div class="list-group">
                {% include 'sidebar.html' %}
            </div>
        </div>
        <div class="col-md-8">
            {% block content %}

            {% endblock %}
        </div>
        
    </div>

    

</body>
</html>

templates/sidebar.html
<a href="{% url 'shedule:shedule_add' %}" class="list-group-item">Добавить задание</a>
<a href="{% url 'shedule:user_add' %}" class="list-group-item">Добавить Препода</a>